<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_book_index' => [[], ['_controller' => 'App\\Controller\\BookController::index'], [], [['text', '/api/books']], [], [], []],
    'api_book_create' => [[], ['_controller' => 'App\\Controller\\BookController::create'], [], [['text', '/api/books']], [], [], []],
    'api_book_show' => [['id'], ['_controller' => 'App\\Controller\\BookController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/books']], [], [], []],
    'api_book_delete' => [['id'], ['_controller' => 'App\\Controller\\BookController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/books']], [], [], []],
    'app_list' => [[], ['_controller' => 'App\\Controller\\ListController::index'], [], [['text', '/list']], [], [], []],
    'book_delete_fro_list' => [['id'], ['_controller' => 'App\\Controller\\ListController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/list']], [], [], []],
    'app_posts' => [[], ['_controller' => 'App\\Controller\\PostsController::index'], [], [['text', '/posts']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_test' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/test']], [], [], []],
];
